
["Custom Gacha Items 20 % of getting nothing ， 有20%的機率不會獲得物品"]
	#Item 1 to 4 name settings for luckyball lv1, use a proper id for item
	# 初級扭蛋 更改物品1 -4 的名稱設定 ， 請使用正確的物品名稱 
	#10% item, 10% 機率物品 
	item1 = "minecraft:name_tag"
	#15% item, 15% 機率物品 
	item2 = "minecraft:slime_ball"
	#20% item, 20% 機率物品 
	item3 = "minecraft:iron_ingot"
	#35% item, 35% 機率物品 
	item4 = "minecraft:coal"
	#
	#[luckyball lv2 中級扭蛋 -------------------------------------------------------]
	#
	#10% item, 10% 機率物品 
	item5 = "minecraft:diamond"
	#15% item, 15% 機率物品 
	item6 = "minecraft:blaze_powder"
	#20% item, 20%機率物品 
	item7 = "minecraft:gold_ingot"
	#35% item, 35% 機率物品 
	item8 = "minecraft:leather"
	#
	#[luckyball lv3 高級扭蛋 -------------------------------------------------------]
	#
	#10% item, 10% 機率物品 
	item9 = "minecraft:netherite_scrap"
	#15% item, 15% 機率物品 
	item10 = "minecraft:ender_pearl"
	#20% item, 20% 機率物品 
	item11 = "minecraft:redstone"
	#35% item, 35% 機率物品 
	item12 = "minecraft:lapis_lazuli"

